version: "3.8"

services:
  plex-to-letterboxd:
    build: .
    container_name: new-plex-to-letterboxd
    restart: unless-stopped
    network_mode: "host"
    environment:
      - TZ=America/Chicago
      - PLEX_URL=${PLEX_URL}
      - PLEX_TOKEN=${PLEX_TOKEN}
      - SCHEDULE_TIME=${SCHEDULE_TIME}
      - PLEX_LIBRARIES=${PLEX_LIBRARIES}
      - EXPORT_DIR=${EXPORT_DIR}
    volumes:
      - /synology/nas/plex-to-letterboxd:/output
    env_file:
      - .env
